version: '2.2'

services:
  gateway:
    build:
      context: ./
      dockerfile: ./build/package/docker/gateway/Dockerfile
    ports:
      - 8080:8080
    tty:
      true
    depends_on:
      - user
  user:
    build:
      context: ./
      dockerfile: ./build/package/docker/user/Dockerfile
    ports:
      - 50051:50051
    tty:
      true
    depends_on: 
      user_db:
        condition: service_healthy
  auth:
    build:
      context: ./
      dockerfile: ./build/package/docker/auth/Dockerfile
    ports:
      - 50052:50052
    tty:
      true
    depends_on: 
      user_db:
        condition: service_healthy
  user_db:
    image: postgres:alpine
    container_name: "user_db"
    environment: 
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
      POSTGRES_HOST: user_db
    ports:
      - 5432:5432
    healthcheck:
      test: [CMD-SHELL, "exit", "0"]
      interval: 1s
      timeout: 5s
      retries: 5
  course:
    build:
      context: ./
      dockerfile: ./build/package/docker/course/Dockerfile
    ports:
      - 50053:50053
    tty:
      true
    depends_on: 
      course_db:
        condition: service_healthy
  course_db:
    build: 
      context: ./build/package/docker/course_db/
      dockerfile: Dockerfile
    container_name: "course_db"
    command: postgres -c port=5433
    environment: 
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
      POSTGRES_HOST: course_db
    ports:
      - 5433:5433
    healthcheck:
      test: [CMD-SHELL, "exit", "0"]
      interval: 1s
      timeout: 5s
      retries: 5
  lesson:
    build:
      context: ./
      dockerfile: ./build/package/docker/lesson/Dockerfile
    ports:
      - 50054:50054
    tty:
      true
    depends_on: 
      lesson_db:
        condition: service_healthy
  lesson_db:
    build: 
      context: ./build/package/docker/lesson_db/
      dockerfile: Dockerfile
    container_name: "lesson_db"
    command: postgres -c port=5434
    environment: 
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
      POSTGRES_HOST: lesson_db
    ports:
      - 5434:5434
    healthcheck:
      test: [CMD-SHELL, "exit", "0"]
      interval: 1s
      timeout: 5s
      retries: 5
  runner:
    build:
      context: ./
      dockerfile: ./build/package/docker/runner/Dockerfile
    ports:
      - 50055:50055
    tty:
      true
    env_file:
      - jdoodle.env