version: '3'

services:
  gateway:
    build:
      context: ./
      dockerfile: ./build/package/docker/gateway/Dockerfile
    ports:
      - 8080:8080
    tty:
      true
    depends_on:
      - user
  user:
    build:
      context: ./
      dockerfile: ./build/package/docker/user/Dockerfile
    ports:
      - 50051:50051
    tty:
      true
    depends_on: 
      user_db:
        condition: service_healthy
  auth:
    build:
      context: ./
      dockerfile: ./build/package/docker/auth/Dockerfile
    ports:
      - 50052:50052
    tty:
      true
    depends_on: 
      user_db:
        condition: service_healthy
  user_db:
    image: postgres:alpine
    container_name: "user_db"
    environment: 
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
      POSTGRES_HOST: user_db
    ports:
      - 5432:5432
    healthcheck:
      test: [CMD-SHELL, "exit", "0"]
      interval: 1s
      timeout: 5s
      retries: 5