name: es-lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Prettier
        run: yarn prettier --write .
        working-directory: ./web
      - name: Lint
        run: yarn run lint
        working-directory: ./web
